### ISSUE TITLE
Option to clear staging authorizations

### ISSUE THREAD

**Issue by mnordhoff** [alexzorin/clear-authz#1]
The `acme-v01` endpoint is currently hardcoded.

A command line option or environment variable to clear authzs from `acme-staging` instead would occasionally be useful.

https://community.letsencrypt.org/t/new-authz-rate-limit-in-staging/61365 is an example. (User already solved it by hacking the URL in the source code.)

**Comment by alexzorin** [comment]
The v1 endpoint hostname can now be provided via the `CLEAR_AUTHZ_SERVER` env variable, defaulting to Let's Encrypt v1 live.
